In [1]:
import pandas as pd

In [2]:
fema_file = 'PublicAssistanceFundedCondensed.csv'
fema_df = pd.read_csv(fema_file)

In [88]:
fema_df.head()
#fema_df['disasterNumber'].value_counts()
fema_df['disasterNumber'].nunique()

813

In [89]:
fema_df['disasterNumber'].value_counts()

1791    14622
1763    10282
4020     8785
1786     6607
1829     5733
4030     5452
1909     5229
4086     4936
4021     4767
1981     4568
4085     4416
1975     4347
1751     4186
4022     3272
1768     3059
4031     2556
3105     2445
1915     2426
1984     2397
1971     2392
1912     2329
1766     2298
1818     2258
4223     2181
1858     2132
1830     2125
1960     2110
1898     2091
1749     2009
1817     1936
        ...
3342        7
3108        6
3263        6
1950        6
3246        5
3358        5
3126        5
3234        5
3304        4
3118        4
4351        4
3244        4
4147        3
4357        3
3253        2
3320        2
4312        2
3155        2
4257        2
3258        1
3245        1
3117        1
3276        1
4362        1
3080        1
3247        1
3341        1
3395        1
3256        1
3142        1
Name: disasterNumber, Length: 813, dtype: int64

In [8]:
state_group = fema_df.groupby(["state"])
state_group.sum()

,disasterNumber,Year,countyCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated
state,,,,,,,
Alabama,18840135,15847016,403660.0,7880,4.521503e+08,3.724654e+08,3.739797e+08
Alaska,2274530,1588638,77357.0,1580,1.886428e+08,1.422229e+08,1.422229e+08
American Samoa,426865,407944,0.0,12180,1.032174e+08,9.323184e+07,9.323184e+07
Arizona,1508577,1194675,3441.0,2376,3.408487e+07,2.724991e+07,2.743388e+07
Arkansas,35729644,33917679,1203201.0,84370,6.589784e+08,5.079457e+08,5.085282e+08

In [23]:
project_amount = state_group['projectAmount'].sum()
fed_funded = state_group['federalShareObligated'].sum()

state_summary_table = pd.DataFrame({"ProjectAmount":project_amount,
                                   "FederalFunded":fed_funded})

In [27]:
state_summary_table["%Funded"] = state_summary_table["FederalFunded"] / state_summary_table["ProjectAmount"]

In [30]:
state_summary_table.reset_index(inplace=True)
state_summary_table

,index,state,FederalFunded,ProjectAmount,%Funded
0,0,Alabama,3.724654e+08,4.521503e+08,0.823764
1,1,Alaska,1.422229e+08,1.886428e+08,0.753927
2,2,American Samoa,9.323184e+07,1.032174e+08,0.903257
3,3,Arizona,2.724991e+07,3.408487e+07,0.799472
4,4,Arkansas,5.079457e+08,6.589784e+08,0.770808
5,5,California,1.507317e+09,1.926804e+09,0.782289
6,6,Colorado,4.058015e+08,5.322027e+08,0.762494
7,7,Connecticut,2.979649e+08,3.944637e+08,0.755367
8,8,Delaware,2.438480e+07,3.262236e+07,0.747487
9,9,District of Columbia,5.489343e+07,6.936634e+07,0.791355
10,10,Federated States of Micronesia,7.399165e+04,9.865553e+04,0.750000
11,11,Florida,9.936745e+08,1.251904e+09,0.793731
12,12,Georgia,4.517195e+08,5.839089e+08,0.773613
13,13,Guam,4.918961e+06,6.512966e+06,0.755257
14,14,Hawaii,3.291443e+07,4.285074e+07,0.768118
15,15,Idaho,3.475696e+07,4.599753e+07,0.755627
16,16,Illinois,2.640799e+08,3.478289e+08,0.759224
17,17,Indiana,2.003813e+08,2.626016e+08,0.763062
18,18,Iowa,1.510526e+09,1.751559e+09,0.862389
19,19,Kansas,4.104872e+08,5.452383e+08,0.752858
20,20,Kentucky,4.517760e+08,5.851595e+08,0.772056
21,21,Louisiana,1.985949e+09,2.276693e+09,0.872295
22,22,Maine,5.237398e+07,7.007600e+07,0.747388
23,23,Maryland,2.773818e+08,3.691512e+08,0.751404
24,24,Massachusetts,5.840199e+08,7.734276e+08,0.755106
25,25,Michigan,5.880680e+07,7.651095e+07,0.768606
26,26,Minnesota,2.450252e+08,3.232285e+08,0.758055
27,27,Mississippi,2.599224e+08,3.385379e+08,0.767779
28,28,Missouri,6.675843e+08,9.011686e+08,0.740798
29,29,Montana,7.066181e+07,9.019220e+07,0.783458
30,30,Nebraska,2.379520e+08,3.181632e+08,0.747893
31,31,Nevada,3.190535e+07,4.177882e+07,0.763673
32,32,New Hampshire,9.341411e+07,1.242982e+08,0.751533
33,33,New Jersey,2.498038e+09,2.848484e+09,0.876971
34,34,New Mexico,2.567732e+08,3.345210e+08,0.767585
35,35,New York,1.538776e+10,1.739684e+10,0.884514
36,36,North Carolina,4.982195e+08,6.520559e+08,0.764075
37,37,North Dakota,4.405033e+08,5.114025e+08,0.861363
38,38,Northern Mariana Islands,3.931803e+07,4.377204e+07,0.898245
39,39,Ohio,1.273085e+08,1.684197e+08,0.755901
40,40,Oklahoma,6.525974e+08,8.543383e+08,0.763863
41,41,Oregon,1.402576e+08,1.845325e+08,0.760070
42,42,Pennsylvania,3.721185e+08,4.917684e+08,0.756695
43,43,Puerto Rico,2.605636e+09,2.667724e+09,0.976726
44,44,Rhode Island,7.069968e+07,8.809649e+07,0.802526
45,45,South Carolina,5.708427e+08,7.208970e+08,0.791851
46,46,South Dakota,2.328579e+08,3.086650e+08,0.754403
47,47,Tennessee,4.840265e+08,5.804341e+08,0.833904
48,48,Texas,4.204050e+09,4.561677e+09,0.921602
49,49,Utah,2.611856e+07,3.458811e+07,0.755131
50,50,Vermont,2.687071e+08,3.104446e+08,0.865556
51,51,Virgin Islands of the U.S.,1.035917e+09,1.078571e+09,0.960453
52,52,Virginia,2.666065e+08,3.522600e+08,0.756846
53,53,Washington,3.112510e+08,4.093090e+08,0.760431
54,54,West Virginia,2.870786e+08,3.763536e+08,0.762790
55,55,Wisconsin,1.251780e+08,1.638645e+08,0.763912
56,56,Wyoming,1.853616e+07,2.463866e+07,0.752320

In [32]:
state_summary_table.to_csv("state_funded.csv", index=False)

In [69]:
weather_state = fema_df.groupby(['state','incidentType']).count()
state_incident_count = pd.DataFrame({"ProjectAmount":weather_state['dcc']})

In [71]:
state_incident_count.reset_index(inplace=True)

In [73]:
state_incident_count.to_csv("incidenttype_count.csv", index=False)

In [75]:
incident_type = fema_df.groupby(["incidentType"])
incident_type.sum().head()

,disasterNumber,Year,countyCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated
incidentType,,,,,,,
Chemical,181764,108756,1934.0,2916,2.178019e+06,1.639099e+06,1.639099e+06
Coastal Storm,381275,189062,6456.0,1928,1.294351e+07,9.790313e+06,9.790313e+06
Earthquake,2581373,1705660,28363.0,18931,2.385950e+08,1.954753e+08,1.954753e+08
Fire,8257871,4873943,179026.0,88688,1.372550e+09,1.087196e+09,1.087196e+09
Flood,161809649,101924342,3096427.0,1713815,4.080427e+09,3.215218e+09,3.215218e+09

In [80]:
incident_amount = incident_type['projectAmount'].sum()
fed_funded_incident = incident_type['federalShareObligated'].sum()

incident_summary_table = pd.DataFrame({"ProjectAmount":incident_amount,
                                   "FederalFunded":fed_funded_incident})

incident_summary_table["%Funded"] = incident_summary_table["FederalFunded"] / incident_summary_table["ProjectAmount"]

incident_summary_table.reset_index(inplace=True)

In [81]:
incident_summary_table.to_csv("incident_funded.csv", index=False)

In [82]:
disaster_count = fema_df.groupby(["disasterNumber"])

,Year,incidentType,title,dcc,damageCategory,projectSize,county,countyCode,state,stateCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated
disasterNumber,,,,,,,,,,,,,,
1733,882,882,882,882,882,882,882,882,882,882,882,882,882,882
1734,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532
1735,1059,1059,1059,1059,1059,1059,1059,1059,1059,1059,1059,1059,1059,1059
1736,716,716,716,716,716,716,716,716,716,716,716,716,716,716
1737,755,755,755,755,755,755,755,755,755,755,755,755,755,755
1738,30,30,30,30,30,30,30,30,30,30,30,30,30,30
1739,93,93,93,93,93,93,93,93,93,93,93,93,93,93
1740,336,336,336,336,336,336,336,336,336,336,336,336,336,336
1741,1251,1251,1251,1251,1251,1251,1251,1251,1251,1251,1251,1251,1251,1251
1742,96,96,96,96,96,96,96,96,96,96,96,96,96,96
1743,71,71,71,71,71,71,71,71,71,71,71,71,71,71
1744,236,236,236,236,236,236,236,236,236,236,236,236,236,236
1745,238,238,238,238,238,238,238,238,238,238,238,238,238,238
1746,242,242,242,242,242,242,242,242,242,242,242,242,242,242
1748,221,221,221,221,221,221,221,221,221,221,221,221,221,221
1749,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009
1750,100,100,100,100,100,100,100,100,100,100,100,100,100,100
1751,4186,4186,4186,4186,4186,4186,4186,4186,4186,4186,4186,4186,4186,4186
1752,452,452,452,452,452,452,452,452,452,452,452,452,452,452
1754,911,911,911,911,911,911,911,911,911,911,911,911,911,911
1755,526,526,526,526,526,526,526,526,526,526,526,526,526,526
1756,58,58,58,58,58,58,58,58,58,58,58,58,58,58
1757,530,530,530,530,530,530,530,530,530,530,530,530,530,530
1758,85,85,85,85,85,85,85,85,85,85,85,85,85,85
1759,37,37,37,37,37,37,37,37,37,37,37,37,37,37
1761,226,226,226,226,226,226,226,226,226,226,226,226,226,226
1763,10282,10282,10282,10282,10282,10282,10282,10282,10282,10282,10282,10282,10282,10282
1764,19,19,19,19,19,19,19,19,19,19,19,19,19,19
1765,52,52,52,52,52,52,52,52,52,52,52,52,52,52
1766,2298,2298,2298,2298,2298,2298,2298,2298,2298,2298,2298,2298,2298,2298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4329,29,29,29,29,29,29,29,29,29,29,29,29,29,29
4330,24,24,24,24,24,24,24,24,24,24,24,24,24,24
4331,250,250,250,250,250,250,250,250,250,250,250,250,250,250
4332,464,464,464,464,464,464,464,464,464,464,464,464,464,464
4333,33,33,33,33,33,33,33,33,33,33,33,33,33,33
4334,93,93,93,93,93,93,93,93,93,93,93,93,93,93
4335,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4336,40,40,40,40,40,40,40,40,40,40,40,40,40,40
4337,438,438,438,438,438,438,438,438,438,438,438,438,438,438
4338,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532
4339,413,413,413,413,413,413,413,413,413,413,413,413,413,413
4340,180,180,180,180,180,180,180,180,180,180,180,180,180,180
4341,28,28,28,28,28,28,28,28,28,28,28,28,28,28
4342,25,25,25,25,25,25,25,25,25,25,25,25,25,25
4343,288,288,288,288,288,288,288,288,288,288,288,288,288,288
4344,75,75,75,75,75,75,75,75,75,75,75,75,75,75
4345,72,72,72,72,72,72,72,72,72,72,72,72,72,72
4346,94,94,94,94,94,94,94,94,94,94,94,94,94,94
4347,14,14,14,14,14,14,14,14,14,14,14,14,14,14
4348,16,16,16,16,16,16,16,16,16,16,16,16,16,16
4349,27,27,27,27,27,27,27,27,27,27,27,27,27,27
4350,40,40,40,40,40,40,40,40,40,40,40,40,40,40
4351,4,4,4,4,4,4,4,4,4,4,4,4,4,4
4352,50,50,50,50,50,50,50,50,50,50,50,50,50,50
4353,29,29,29,29,29,29,29,29,29,29,29,29,29,29
4354,51,51,51,51,51,51,51,51,51,51,51,51,51,51
4355,8,8,8,8,8,8,8,8,8,8,8,8,8,8
4356,40,40,40,40,40,40,40,40,40,40,40,40,40,40
4357,3,3,3,3,3,3,3,3,3,3,3,3,3,3
4362,1,1,1,1,1,1,1,1,1,1,1,1,1,1